name: ai_app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  dartz: ^0.10.1
  firebase_auth: ^5.4.2
  provider: ^6.1.2
  dio: ^5.8.0+1
  geolocator: ^13.0.2
  either_dart: ^1.0.0
  http: ^1.3.0
  get_it: ^8.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
