// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJMclnpwmGGw2DVShrJu8ktA1RN7jr2Qg',
    appId: '1:672553009694:web:75cd6d4645eeaa8ff2a40f',
    messagingSenderId: '672553009694',
    projectId: 'ai-app-e5d94',
    authDomain: 'ai-app-e5d94.firebaseapp.com',
    storageBucket: 'ai-app-e5d94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7GhRx2elvV-ouHoNN_xdd5pncX_tP9SQ',
    appId: '1:672553009694:android:d9c019aa1ddaf575f2a40f',
    messagingSenderId: '672553009694',
    projectId: 'ai-app-e5d94',
    storageBucket: 'ai-app-e5d94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDvF2-Qip2aEbxA0ENS0QsZlM9OZ2E_k8',
    appId: '1:672553009694:ios:93b4b82682f281a2f2a40f',
    messagingSenderId: '672553009694',
    projectId: 'ai-app-e5d94',
    storageBucket: 'ai-app-e5d94.firebasestorage.app',
    iosBundleId: 'com.example.aiApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDvF2-Qip2aEbxA0ENS0QsZlM9OZ2E_k8',
    appId: '1:672553009694:ios:93b4b82682f281a2f2a40f',
    messagingSenderId: '672553009694',
    projectId: 'ai-app-e5d94',
    storageBucket: 'ai-app-e5d94.firebasestorage.app',
    iosBundleId: 'com.example.aiApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJMclnpwmGGw2DVShrJu8ktA1RN7jr2Qg',
    appId: '1:672553009694:web:bb02b019e13d11fdf2a40f',
    messagingSenderId: '672553009694',
    projectId: 'ai-app-e5d94',
    authDomain: 'ai-app-e5d94.firebaseapp.com',
    storageBucket: 'ai-app-e5d94.firebasestorage.app',
  );
}
